- name: Playbook1
  hosts: localhost
  vars:
   URL: global.clouditz.com
  vars_files: files.yml   
  tasks:
  - name: print message_1
    debug:
     msg: "{{URL}}"
     #  vars:
     # URL: "hello bhai"
