- name: loop name
  hosts: all
  tasks: 
    - name: print city name
      debug: 
        msg: "all my city name: {{item}}"
      loop:
        - nag
        - pune
        - mumbai
        - chandrapur

    - name: install packages
      become: true
      apt: 
        name: "{{item}}"
        state: latest
      loop:
        - mysql
        - nginx