- name: playbook_2
  hosts: all
  gather_facts: yes
  tasks:
    - name: Print the task_1
      debug:
        msg: "{{ansible_distribution}}" 
      when: ansible_distribution == "Ubuntu" and ansible_os_family == "Debian"
      when: (ansible_distribution == "Ubuntu" and ansible_os_family == "Debian") or (ansible_distribution == "Ubuntu" and ansible_os_family 