---
# tasks file for websrv
- name: update 
  apt: 
    update_cache: yes
    
- name: install java
  apt:  
    name: "{{ item }}"
    state: present
    loop:
      - openjdk-8-jre-headless 
      - unzip

- name: download web-application
  get_url:
    url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.81/bin/apache-tomcat-8.5.81.tar.gz
    dest: /mnt


- name: extracting zip file
  command: tar -xzf /mnt/apache-tomcat-8.5.81.tar.gz -C /mnt

- name: 
  copy:
  srv: /home/ubuntu/student.war
  dest:/mnt/apache-tomcat-8.5.81.tar.gz/studentaap

- name: start and enableing tomcat
  command: /mnt/apache-tomcat-8/v8.5.81/bin/catalina.sh start